package dev.shibasis.dependeasy.dagger

import kotlinx.serialization.json.*
import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.MapProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.*

@CacheableTask
abstract class GenerateDaggerTask : DefaultTask() {
    @get:Input abstract val moduleName: Property<String>
    @get:Input abstract val buildName: Property<String>
    @get:Input abstract val engineVersion: Property<String>
    @get:Input abstract val moduleSource: Property<String>
    @get:Input abstract val browserImage: Property<String>
    @get:Input abstract val gradleProperties: MapProperty<String, String>
    @get:Input abstract val declarations: ListProperty<String>
    @get:InputFile @get:PathSensitive(PathSensitivity.NONE) abstract val runtimeSource: RegularFileProperty
    @get:OutputDirectory abstract val outputDirectory: DirectoryProperty
    @get:OutputFile abstract val moduleConfiguration: RegularFileProperty

    @TaskAction fun generate() {
        val targets = declarations.get().map { Json.parseToJsonElement(it).jsonObject }
            .filter { it.text("platform") in setOf("portable", "linux") }
        val methods = targets.map { target ->
            val name = target.text("task").removePrefix(":")
            val recipes = target.getValue("recipes").jsonArray.map { it.jsonPrimitive.content }
            if (recipes.isNotEmpty()) return@map "  @func()\n  async $name(): Promise<string> {\n" +
                "    const outputs = await Promise.all([${recipes.joinToString(", ") { "this.$it()" }}])\n    return outputs.join(\"\\n\")\n  }"
            val output = target["output"]?.jsonPrimitive?.content
            val deploy = target.text("effect") == "deploy"
            val environments = target.getValue("environments").jsonArray
            val selectEnvironment = deploy && environments.isNotEmpty()
            val defaultEnvironment = environments.firstOrNull { it.jsonPrimitive.content == "prod" } ?: environments.firstOrNull()
            val environmentParameter = if (selectEnvironment) ", targetEnv: string = $defaultEnvironment" else ""
            val parameters = if (deploy) "cloudflareApiToken: Secret$environmentParameter" else ""
            val result = if (output == null) "stdout()" else "directory(${quote("/work/${buildName.get()}/$output")})"
            val environmentBinding = if (selectEnvironment) ".withEnvVariable(\"TARGET_ENV\", checkedEnvironment(targetEnv, $environments))" else ""
            val secret = if (deploy) ".withSecretVariable(\"CLOUDFLARE_API_TOKEN\", cloudflareApiToken)$environmentBinding" else ""
            val external = target.text("kind") == "external"
            val runtime = if (target.text("runner") == "browser") "browserWorkspace(${quote(browserImage.get())})" else if (external) "commandWorkspace()" else "workspace()"
            val commands = if (external) target.getValue("commands").jsonArray.map { it.toString() }
                else listOf("[\"./gradlew\", ${quote(target.text("task"))}, \"--console=plain\"]")
            "  @func()\n  async $name($parameters): Promise<${if (output == null) "string" else "Directory"}> {\n" +
                "    return (await this.runtime().$runtime)$secret${commands.joinToString("") { ".withExec($it)" }}.$result\n  }"
        }
        val workers = targets.filter { "worker" in it }.associate { it.text("worker") to it.text("task") }
        val workerEnvironments = targets.filter { "worker" in it }.associate { it.text("worker") to it.getValue("environments") }
        val workerMethod = if (workers.isEmpty()) "" else """
            @func()
            async deployWorker(name: string, cloudflareApiToken: Secret, targetEnv: string = "prod"): Promise<string> {
              const targets: Record<string, string> = ${Json.encodeToString(JsonObject.serializer(), JsonObject(workers.mapValues { JsonPrimitive(it.value) }))}
              const environments: Record<string, string[]> = ${JsonObject(workerEnvironments)}
              const target = targets[name]
              if (!target) throw new Error(`Unknown worker '${'$'}{name}'; choose ${'$'}{Object.keys(targets).join(", ")}`)
              return (await this.runtime().workspace()).withSecretVariable("CLOUDFLARE_API_TOKEN", cloudflareApiToken)
                .withEnvVariable("TARGET_ENV", checkedEnvironment(targetEnv, environments[name])).withExec(["./gradlew", target, "--console=plain"]).stdout()
            }
        """.trimIndent()
        val source = """
            // Generated by Gradle generateDagger. Edit Gradle declarations or Dependeasy, then regenerate.
            import { Container, Directory, Secret, argument, object, func } from "@dagger.io/dagger"
            import { BuildRuntime, SOURCE_IGNORES, checkedEnvironment } from "./runtime.js"

            @object()
            export class ${moduleName.get()} {
              source: Directory
              reaktor: Directory
              constructor(@argument({ ignore: SOURCE_IGNORES }) source: Directory, @argument({ ignore: SOURCE_IGNORES }) reaktor: Directory) {
                this.source = source; this.reaktor = reaktor
              }
              private runtime(): BuildRuntime { return new BuildRuntime(this.source, this.reaktor, ${quote(buildName.get())}, ${JsonObject(gradleProperties.get().mapKeys { "ORG_GRADLE_PROJECT_${it.key}" }.mapValues { JsonPrimitive(it.value) })}) }
              @func()
              async toolchain(): Promise<Container> { return this.runtime().toolchain() }
              @func()
              async androidToolchain(): Promise<Container> { return this.runtime().androidToolchain() }
              @func()
              async workspace(): Promise<Container> { return this.runtime().workspace() }
        """.trimIndent() + "\n" + methods.joinToString("\n") + "\n" + workerMethod.prependIndent("  ") + "\n}\n"
        outputDirectory.get().asFile.apply {
            mkdirs(); resolve("index.ts").writeText(source)
            runtimeSource.get().asFile.copyTo(resolve("runtime.ts"), overwrite = true)
        }
        moduleConfiguration.get().asFile.apply {
            parentFile.mkdirs()
            writeText(buildJsonObject {
                put("name", buildName.get())
                put("engineVersion", "v${engineVersion.get()}")
                putJsonObject("sdk") { put("source", "typescript") }
                put("source", moduleSource.get())
            }.toString() + "\n")
        }
    }

    private fun JsonObject.text(key: String) = getValue(key).jsonPrimitive.content
    private fun quote(value: String) = JsonPrimitive(value).toString()
}
