include("${CMAKE_CURRENT_LIST_DIR}/reaktor.cmake")

macro(reaktor_platform)
    if(iOS)
        setup_ios()
    endif()
endmacro()

macro(reaktor_configuration)
    if(APPLE)
        enable_language(OBJC OBJCXX)
    endif()
    init()
endmacro()

function(reaktor_library name)
    cmake_parse_arguments(DEPE "HERMES;FOUNDATION;FBJNI;FLATBUFFERS" "" "" ${ARGN})
    if(ANDROID)
        add_library(${name} SHARED ${common} ${droid})
        target_link_libraries(${name} PUBLIC android log)
    elseif(APPLE)
        add_library(${name} STATIC ${common} ${darwin})
    else()
        add_library(${name} STATIC ${common})
    endif()
    target_include_directories(${name} PUBLIC
        "${CMAKE_CURRENT_SOURCE_DIR}/src/commonMain/cpp"
        "${CMAKE_CURRENT_SOURCE_DIR}/src/commonMain/cpp/include"
        ${REAKTOR_NATIVE_PUBLIC_INCLUDE_DIRS})
    target_include_directories(${name} PRIVATE
        "${CMAKE_CURRENT_SOURCE_DIR}/src/androidMain/cpp"
        "${CMAKE_CURRENT_SOURCE_DIR}/src/iosMain/cpp")
    if(DEPE_FLATBUFFERS)
        target_include_directories(${name} PUBLIC "${REAKTOR_SOURCE_ROOT}/.github_modules/flatbuffers/include")
    endif()
    if(DEPE_FOUNDATION AND APPLE)
        target_compile_options(${name} PRIVATE -fobjc-arc)
        target_link_libraries(${name} PUBLIC "-framework Foundation")
    endif()
    if(DEPE_FBJNI)
        if(ANDROID)
            target_link_libraries(${name} PUBLIC fbjni::fbjni)
        endif()
    endif()
    if(DEPE_HERMES)
        configure_hermes()
        if(ANDROID)
            if(NOT TARGET jsi)
                add_library(jsi SHARED "${REAKTOR_SOURCE_ROOT}/.github_modules/hermes/API/jsi/jsi/jsi.cpp")
                target_include_directories(jsi PUBLIC "${REAKTOR_SOURCE_ROOT}/.github_modules/hermes/API/jsi")
            endif()
            target_link_libraries(${name} PUBLIC jsi hermes-engine::hermesvm)
        else()
            target_link_libraries(${name} PUBLIC hermesvm jsi)
        endif()
    endif()
    if(REAKTOR_INTEROP_EXPORTS_HEADER)
        target_compile_definitions(${name} PRIVATE REAKTOR_INTEROP_EXPORTS_HEADER="${REAKTOR_INTEROP_EXPORTS_HEADER}")
    endif()
    fi_link_dependencies(${name})
endfunction()
