package dev.shibasis.dependeasy.versions

import dev.shibasis.dependeasy.Versions
import dev.shibasis.dependeasy.toolchain.ToolchainVersions

object KotlinLibraries {
    const val Stdlib = "org.jetbrains.kotlin:kotlin-stdlib:${Versions.SDK.Kotlin}"
    const val CoroutinesSwing = "org.jetbrains.kotlinx:kotlinx-coroutines-swing:${Versions.Coroutines}"
    const val CoroutinesAndroid = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.Coroutines}"
    const val CoroutinesPlayServices = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services:${Versions.Coroutines}"
    const val CoroutinesGuava = "org.jetbrains.kotlinx:kotlinx-coroutines-guava:${Versions.Coroutines}"
    const val CoroutinesJs = "org.jetbrains.kotlinx:kotlinx-coroutines-core-js:${Versions.Coroutines}"
    const val KoinCore = "io.insert-koin:koin-core:${Versions.Koin}"
    const val KoinCompose = "io.insert-koin:koin-compose:${Versions.Koin}"
    const val KoinAnnotations = "io.insert-koin:koin-annotations:${Versions.KoinAnnotations}"
    const val KtorLogging = "io.ktor:ktor-client-logging:${Versions.Ktor}"
    const val KtorDarwin = "io.ktor:ktor-client-darwin:${Versions.Ktor}"
    const val Benchmark = "org.jetbrains.kotlinx:kotlinx-benchmark-runtime:${ToolchainVersions.KotlinBenchmark}"
    const val KtorOkHttp = "io.ktor:ktor-client-okhttp:${Versions.Ktor}"
    const val KtorJs = "io.ktor:ktor-client-js:${Versions.Ktor}"
    const val KtorCore = "io.ktor:ktor-client-core:${Versions.Ktor}"
    const val KtorContentNegotiation = "io.ktor:ktor-client-content-negotiation:${Versions.Ktor}"
    const val KtorJson = "io.ktor:ktor-serialization-kotlinx-json:${Versions.Ktor}"
    const val Kermit = "co.touchlab:kermit:${Versions.Kermit}"
    const val KermitCrashlytics = "co.touchlab:kermit-crashlytics:${Versions.Kermit}"
    const val ArrowBom = "io.arrow-kt:arrow-stack:2.2.0"
    const val ArrowCore = "io.arrow-kt:arrow-core"
    const val ArrowCoroutines = "io.arrow-kt:arrow-fx-coroutines"
    const val ArrowResilience = "io.arrow-kt:arrow-resilience"
    const val WrappersBom = "org.jetbrains.kotlin-wrappers:kotlin-wrappers-bom:${Versions.KotlinJSWrappers}"
    fun wrapper(name: String) = "org.jetbrains.kotlin-wrappers:kotlin-$name"
    const val AtomicFu = "org.jetbrains.kotlinx:atomicfu:0.28.0"
    const val CoroutinesCore = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.Coroutines}"
    const val CoroutinesDebug = "org.jetbrains.kotlinx:kotlinx-coroutines-debug:${Versions.Coroutines}"
    const val CoroutinesJdk8 = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:${Versions.Coroutines}"
    const val CoroutinesReactor = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor:${Versions.Coroutines}"
    const val CoroutinesTest = "org.jetbrains.kotlinx:kotlinx-coroutines-test:${Versions.Coroutines}"
    const val DateTime = "org.jetbrains.kotlinx:kotlinx-datetime:0.7.1"
    const val ImmutableCollections = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.4.0"
    const val Io = "org.jetbrains.kotlinx:kotlinx-io-core:0.3.1"
    const val KtorMock = "io.ktor:ktor-client-mock:${Versions.Ktor}"
    const val KtorNetwork = "io.ktor:ktor-network:${Versions.Ktor}"
    const val Reflect = "org.jetbrains.kotlin:kotlin-reflect:${Versions.SDK.Kotlin}"
    const val SerializationCore = "org.jetbrains.kotlinx:kotlinx-serialization-core:${Versions.Serialization}"
    const val SerializationCoreJvm = "org.jetbrains.kotlinx:kotlinx-serialization-core-jvm:${Versions.Serialization}"
    const val SerializationJson = "org.jetbrains.kotlinx:kotlinx-serialization-json:${Versions.Serialization}"
    const val SerializationJsonJvm = "org.jetbrains.kotlinx:kotlinx-serialization-json-jvm:${Versions.Serialization}"
    const val SerializationProtobuf = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf:${Versions.Serialization}"
    const val SerializationProtobufJvm = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf-jvm:${Versions.Serialization}"
}
