cmake_minimum_required(VERSION 4.0)
include("../dependeasy/cmake/api.cmake")
reaktor_platform()
project(ReaktorFFI LANGUAGES C CXX)
reaktor_configuration()
reaktor_library(ReaktorFFI HERMES FBJNI)

if(NOT ANDROID AND NOT iOS)
    add_executable(interopHostTest src/commonTest/cpp/RuntimeTest.cpp)
    target_link_libraries(interopHostTest PRIVATE ReaktorFFI)
endif()
