package dev.shibasis.dependeasy.web


import dev.shibasis.dependeasy.common.Configuration
import org.gradle.api.Project
import org.gradle.kotlin.dsl.get
import org.gradle.kotlin.dsl.invoke
import org.gradle.kotlin.dsl.named
import org.gradle.kotlin.dsl.the
import org.gradle.kotlin.dsl.withType
import org.gradle.language.jvm.tasks.ProcessResources
import org.jetbrains.kotlin.gradle.dsl.JsSourceMapEmbedMode
import org.jetbrains.kotlin.gradle.dsl.KotlinJsCompile
import org.jetbrains.kotlin.gradle.dsl.KotlinMultiplatformExtension
import org.jetbrains.kotlin.gradle.targets.js.dsl.ExperimentalDistributionDsl
import org.jetbrains.kotlin.gradle.targets.js.dsl.ExperimentalMainFunctionArgumentsDsl
import org.jetbrains.kotlin.gradle.targets.js.dsl.KotlinJsTargetDsl
import org.jetbrains.kotlin.gradle.targets.js.ir.KotlinJsIrCompilation
import org.jetbrains.kotlin.gradle.targets.js.npm.PackageJson
import org.jetbrains.kotlin.gradle.targets.js.webpack.KotlinWebpackConfig
import org.jetbrains.kotlin.gradle.targets.js.webpack.WebpackDevtool
import org.jetbrains.kotlin.gradle.targets.js.yarn.YarnLockMismatchReport
import org.jetbrains.kotlin.gradle.targets.js.yarn.YarnPlugin
import org.jetbrains.kotlin.gradle.targets.js.yarn.YarnRootExtension
import java.io.File

class WebConfiguration: Configuration<KotlinJsTargetDsl>() {
    var moduleName: String? = null
    var packageJson: File? = null

    internal var packageJsonCustomizer: (PackageJson.() -> Unit)? = null
    private set
    internal var webpackConfig: (KotlinWebpackConfig.() -> Unit) = {}
    private set


    fun packageJsonCustomizer(fn: PackageJson.() -> Unit) {
        this.packageJsonCustomizer = fn
    }

    fun webpackConfig(fn: KotlinWebpackConfig.() -> Unit) {
        this.webpackConfig = fn
    }
}


@OptIn(ExperimentalMainFunctionArgumentsDsl::class, ExperimentalDistributionDsl::class)
fun KotlinMultiplatformExtension.web(
    configuration: WebConfiguration.() -> Unit = {}
) {
    val configure = WebConfiguration().apply(configuration)
//    configure.packageJson?.apply(project::buildTasksFromScripts)

    js(IR) {
//        moduleName = "index"
        compilerOptions {
            target.set("es2015")
            sourceMap.set(false)
            sourceMapEmbedSources.set(JsSourceMapEmbedMode.SOURCE_MAP_SOURCE_CONTENT_NEVER)
            freeCompilerArgs.add("-Xes-long-as-bigint")
            freeCompilerArgs.add("-XXLanguage:+JsAllowExportingSuspendFunctions")
            freeCompilerArgs.add("-Xir-minimized-member-names=false")
        }
        useEsModules()
        nodejs {
            binaries.library()
            passProcessArgvToMainFunction()
        }
        generateTypeScriptDefinitions()
        browser {
            binaries.library()
            commonWebpackConfig {
                cssSupport {
                    enabled.set(true)
                }
                webpackTask { sourceMaps = false }
                runTask     { sourceMaps = false }
                devtool = WebpackDevtool.NOSOURCES_SOURCE_MAP
                configure.webpackConfig(this)
            }

            testTask {
                enabled = false
            }
            project.tasks.named { it == "checkComposeUiTestConfigurationForJs" }.configureEach {
                enabled = false
            }

            distribution {
                outputDirectory.set(project.projectDir.resolve("ts/export"))
            }
        }
        compilations["main"].packageJson {
            configure.moduleName?.apply { name = this }
            configure.packageJsonCustomizer?.invoke(this)
        }
        if (!project.pluginManager.hasPlugin("org.jetbrains.compose")) {
            project.tasks.named<ProcessResources>(compilations["test"].processResourcesTaskName) {
                from(project.skikoRuntime(compilations["test"])) { exclude("META-INF/**") }
            }
        }

        configure.targetModifier(this)
    }

    sourceSets {
        jsMain {
            kotlin.srcDir("ts/import")
            configure.sourceSetModifier(this)
            dependencies {
                configure.dependencies(this)
            }
        }
    }

    project.plugins.withType<YarnPlugin> {
        project.the<YarnRootExtension>().yarnLockMismatchReport = YarnLockMismatchReport.WARNING
        project.the<YarnRootExtension>().reportNewYarnLock = false
        project.the<YarnRootExtension>().yarnLockAutoReplace = false
    }

    project.afterEvaluate {
        val webpackConfigDir = project.projectDir.resolve("webpack.config.d")
        if (!webpackConfigDir.exists()) webpackConfigDir.mkdirs()

        webpackConfigDir.resolve("99-prod-sanity.js").writeText("""
            // Generated by dependeasy WebConfiguration
            // Preserves class names for Reaktor graph stability and sane debugging
            const TerserPlugin = require('terser-webpack-plugin');
            config.optimization = config.optimization || {};
            config.optimization.minimizer = [
                new TerserPlugin({
                    terserOptions: {
                        keep_classnames: true,
                        keep_fnames: true
                    }
                })
            ];
        """.trimIndent())
    }
}

private fun Project.skikoRuntime(compilation: KotlinJsIrCompilation) = provider {
    configurations.getByName(compilation.runtimeDependencyConfigurationName).incoming.resolutionResult.allComponents
        .mapNotNull { component -> component.moduleVersion?.takeIf { it.group == "org.jetbrains.skiko" }?.version }
        .distinct()
        .map { zipTree(configurations.detachedConfiguration(dependencies.create("org.jetbrains.skiko:skiko-js-wasm-runtime:$it")).singleFile) }
}
